services:
  web:
    build: .
    ports:
      - "8080:80"
    develop:
      watch:
        - action: sync
          path: ./packages
          target: /app
    volumes:
      - appdata:/app
volumes:
  appdata: